name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          cd my-app
          npm ci
      - run: |
          pwd
          npm run format:check
      - run: |
          pwd
          npm test -- --coverage
        env:
          CI: true