name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      wd: ./my-app
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
        working-directory: ${{ env.wd }}
      - run: npm run format:check
        working-directory: ${{ env.wd }}
      - run: npm test -- --coverage
        working-directory: ${{ env.wd }}
        env:
          CI: true