name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-on-windows:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: powershell
        run: Get-Location
      - name: bash
        run: pwd
        shell: bash